### PR TITLE
Update Agent.py

### PR DESCRIPTION
**Pull request by jhanm12**
Add Retries

### CODE REVIEW

**Comment by jhanm12** [comment]
Positive Test Case Logs (Used Correct Execution Server - Got connected in the 1st retry itself)- http://allure.cisco.com/ws/jhanm-ott/cafykit/work/archive/test_bootup_20230316-040456_p60035/reports/index.html

Negative Test Case Logs (Tried it from a server, from where it can never connect to the PDU - To check if the 3 retries are executed.) - http://allure.cisco.com/ws/jhanm-ott/cafykit/work/archive/test_bootup_20230316-035951_p2654/reports/index.html


Tested it by creating a virtual env - source /ws/jhanm-ott/Power-Cycler/yourenv/bin/activate

**Comment by shreyashah** [comment]
is this importing cafykit utils? 
I am thinking to not have custom cafykit code in any external plugin.

**Comment by jhanm12** [comment]
Ya, there wasn’t any direct retry parameter present in the http.client.HTTPSConnection module. I could add a direct while loop for these retries but Helper module is providing proper logging in Cafy logs as well.

**Comment by jhanm12** [comment]
And I think this codebase fork is only used by cafykit

**Comment by jhanm12** [comment]
@shreyashah Updated it, according to your review comments.

Test Logs - http://allure.cisco.com/ws/jhanm-ott/cafykit/work/archive/test_bootup_20230317-020601_p70112/reports/index.html

**Review by shreyashah — APPROVED** [review]

**Pull request merged**
